version: 2.1
orbs:
  codecov: codecov/codecov@3.0.0
jobs:
  build:
    working_directory: ~/code
    docker:
#       - image: circleci/android:api-30
      - image: ccistaging/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew testDebug

#       - run: ./gradlew assembleDebug
      - run: ./gradlew assembleRelease
      - store_artifacts:
          name: Wits_Academy
          path: app/build/outputs/apk/
          destination: apks/
      - store_test_results:
          path: app/build/test-results
      - run: ./gradlew testDebugUnitTest jacocoTestReport
      - run:
          name: Upload code coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash) -f app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml

   
#   example-job:
#     working_directory: ~/code
#     docker:
#       # replace with your preferred image
#       - image: cimg/base:stable
#     steps:
#       - codecov/upload:
#           file: app/build 
#           token: env_var_name
#           upload_name: CODECOV 
#           url: https://app.codecov.io/gh/zsmhlubi 
#           validate_url: true 
#       - run: |
#           curl -Os https://uploader.codecov.io/latest/linux/codecov 
#           chmod +x codecov
#           ./codecov
# workflows:
#   build_and_deploy:
#     jobs:
#       - build
#       - example-job