version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
#       - image: circleci/android:api-30
      - image: ccistaging/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew testDebug
      - run_ui_tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-29;default;x86

      - run: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
      - store_test_results:
          path: app/build/test-results
